QD-1060 Remove Submodule dependency `querypie-proto`
chequer-io/mongosh pull request #59
Opened 2023-04-28 02:44 UTC by 134130

- `chequer-io/querypie-proto`와 종속성을 제거합니다.
  - submodule 관계를 떼어냅니다.

2023-04-28 02:50 UTC, tony-jang reviewed
요렇게 querypie-proto 의존성 제거하게 되면 그 뒤에 mongoShell.proto가 변경되어야 할때 엔진에도 변경점이 반영되어야 해서 querypie-proto 쪽도 같이 변경되어야 할 거 같은데 계획해두신 방향이 있나요?

2023-04-28 03:15 UTC, 134130 commented
> 요렇게 querypie-proto 의존성 제거하게 되면 그 뒤에 mongoShell.proto가 변경되어야 할때 엔진에도 변경점이 반영되어야 해서 querypie-proto 쪽도 같이 변경되어야 할 거 같은데 계획해두신 방향이 있나요?

어쩐지~~~~~ 뭔가 어디서 작업을 하나 더 해야할 것 같던데 어딘지 기억이 안났거든요~~ 감사합니다~~~~

2023-04-28 05:38 UTC, 134130 commented
@tony-jang @Web-Engine 
- https://github.com/chequer-io/mongosh-proto 
- 해당 레포에서 관리합니다.

2023-05-02 01:38 UTC, Web-Engine requested changes

2023-05-02 01:38 UTC, Web-Engine commented on plugins/mongo-shell-server/package.json
> +    "build:proto": "ncp ./node_modules/@chequer-io/mongosh-proto/grpc-namespaces.ts ./src/grpc-namespaces.ts && ncp ./node_modules/@chequer-io/mongosh-proto/mongoShell.proto ./src/mongoShell.proto",
dependency로 분리했는데 해당 파일을 강제로 복사해 오는 구조가 굉장히 이상 한 것 같습니다.
@chequer-io/mongosh-proto 를 그대로 사용 하는 방향은 어려울까요?

2023-05-04 11:43 UTC, 134130 commented on plugins/mongo-shell-server/package.json
> +    "build:proto": "ncp ./node_modules/@chequer-io/mongosh-proto/grpc-namespaces.ts ./src/grpc-namespaces.ts && ncp ./node_modules/@chequer-io/mongosh-proto/mongoShell.proto ./src/mongoShell.proto",
@Web-Engine 간접 참조로 바꿨는데, engine-backend 빌드에서 한 번 테스트 해봐야할 것 같습니다. prerelease로 배포 부탁드려도 될까요?

2023-05-04 13:16 UTC, 134130 commented on plugins/mongo-shell-server/package.json
> +    "build:proto": "ncp ./node_modules/@chequer-io/mongosh-proto/grpc-namespaces.ts ./src/grpc-namespaces.ts && ncp ./node_modules/@chequer-io/mongosh-proto/mongoShell.proto ./src/mongoShell.proto",
prerelease로 배포 및 동작 확인 이상 없습니다.

2023-05-10 04:49 UTC, Web-Engine requested changes

2023-05-10 04:49 UTC, Web-Engine commented on plugins/mongo-shell-server/src/server.ts
> +// @ts-nocheck
rxjs 버전 문제로 오류가 발생한 부분을 @ts-nocheck로 무시하고 있습니다.
mongosh-proto와 mongo shell server의 rxjs 버전을 통일 시켜야 할 것 같습니다.

기존 동작을 최대한 바꾸지 않기 위해서 mongo shell server의 rxjs 버전에 맞춰 작업하는게 좋을 것 같습니다.

2023-05-10 04:59 UTC, 134130 commented on plugins/mongo-shell-server/src/server.ts
> +// @ts-nocheck
수정된 proto를 같은 버전으로 배포하여 해당 라인 삭제만 진행했습니다.

2023-05-10 05:19 UTC, Web-Engine approved these changes

2023-05-10 07:24 UTC, merged